---

- name: Create mount points
  file:
    dest: "{{ item.dir }}"
    state: directory
  with_items: nfs_client_mountpoints


- name: Mount filesystems
  mount:
    name: "{{ item.dir }}"
    src: "{{ item.dev }}"
    fstype: nfs4
    state: mounted 
  with_items: nfs_client_mountpoints
